"""First commit

Revision ID: f5c6622e600a
Revises: 
Create Date: 2023-07-26 16:37:09.361514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f5c6622e600a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borderdb',
                    sa.Column('border_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('record_at', sa.DateTime(), nullable=False),
                    sa.Column('border', sa.String(), nullable=False),
                    sa.Column('cars', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('border_id')
                    )
    op.create_index(op.f('ix_borderdb_border_id'), 'borderdb', ['border_id'], unique=True)
    op.create_table('datadb',
                    sa.Column('data_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('record_at', sa.Date(), nullable=False),
                    sa.Column('border', sa.String(), nullable=False),
                    sa.Column('status', sa.String(), nullable=False),
                    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('data_id')
                    )
    op.create_index(op.f('ix_datadb_border'), 'datadb', ['border'], unique=False)
    op.create_index(op.f('ix_datadb_data_id'), 'datadb', ['data_id'], unique=True)
    op.create_index(op.f('ix_datadb_record_at'), 'datadb', ['record_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datadb_record_at'), table_name='datadb')
    op.drop_index(op.f('ix_datadb_data_id'), table_name='datadb')
    op.drop_index(op.f('ix_datadb_border'), table_name='datadb')
    op.drop_table('datadb')
    op.drop_index(op.f('ix_borderdb_border_id'), table_name='borderdb')
    op.drop_table('borderdb')
    # ### end Alembic commands ###
